
export const SerieErorrs =  {
    SERIE_NOT_FOUND: 'SERIE_NOT_FOUND',
    SERIE_SCRIPT_NOT_FOUND: 'SERIE_SCRIPT_NOT_FOUND',
    SERIE_SYSTEM_ERR: 'SERIE_SYSTEM_ERR',
    SERIE_SCRIPT_NOT_PROVIDED: 'SERIE_SCRIPT_NOT_PROVIDED'
}